name: CI-master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: get Version from source.extension.vsixmanifest, and append version with run_number
        run: |
          $manifestPath = '${{ github.workspace }}\Mocking.Helpers\Mocking.Helpers.Vsix\source.extension.vsixmanifest'
          $manifestXml = [xml](Get-Content $manifestPath -Raw)
          $version = $manifestXml.PackageManifest.Metadata.Identity.Version
          $split = $version.Split('.')
          $version = $split[0] + '.' + $split[1] + '.' + $split[2] + '.' + ${{ github.run_number }}
          echo "APP_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          $manifestXml.PackageManifest.Metadata.Identity.Version = $version
          $manifestXml.save($manifestPath)
          
      - name: Print content of source.extension.vsixmanifest
        run: get-content .\Mocking.Helpers\Mocking.Helpers.Vsix\source.extension.vsixmanifest
      
      - name: print APP_VERSION
        run: Write-Host $APP_VERSION

      - name: add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: setup nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
      
      - name: nuget restore
        run: nuget restore Mocking.Helpers.sln
      
      - name: build solution
        run:  msbuild Mocking.Helpers.sln -t:rebuild -property:Configuration=Release

      - name: rename Mocking.Helpers.vsix to Mocking.Helpers.W.X.Y.Z.vsix
        run:  ren ${{ github.workspace }}\Mocking.Helpers\Mocking.Helpers.vsix\bin\Release\Mocking.Helpers.vsix Mocking.Helpers.${{ env.APP_VERSION }}.vsix

      - name: create artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mocking.Helpers.${{ env.APP_VERSION }}.vsix
          path: ${{ github.workspace }}\Mocking.Helpers\Mocking.Helpers.vsix\bin\Release\Mocking.Helpers.${{ env.APP_VERSION }}.vsix
